### ISSUE TITLE
With Weapon Randomiser on, Weapon and tool Switching has massive cooldown on (almost) all items, sometimes seemingly infinate

### ISSUE THREAD

**Issue by LeakingAmps** [JamSnack/TRandomizer-Mod#2]
Title. All but one weapon to date (with weapon randomization on), has such a large weapon switch cooldown that it makes tools and weapons unusable, and sometimes softlocks your game, as during weapon switch cooldown, you cannot log out (if it's on your cursor), change gear, manage inventory, etc.

As much as I enjoy the random stats etc, the fact that it makes most weapons and tools unusable and can softlock your game (along with messing up block placing with that same cooldown issue), means I have to turn it off for the game to be playable.

**Comment by JamSnack** [comment]
Hmm.

I don’t necessarily understand the problem enough to provide a conclusive answer, but what I can tell you is that the only thing my mod alters is the code that is run when an NPC spawns.

Terraria seems to run more slowly whenever your game lags because it executes game code locally each frame, (this may not be fact but it’s an educated guess). If this is true, then your problem may be caused by some conflict between the mods you have installed running code together that takes your computer a long time to work out. I.e. the problem may just be your PC’s specs.

**Comment by LeakingAmps** [comment]
I think I might have the wrong randomizer mod's repo here. Whoops!
